### ISSUE TITLE
Your gmail username and password are committed to this repo in plaintext

### ISSUE THREAD

**Issue by benjamincburns** [mackmcconnell/yocuties#1]
See `config/application.yml`

**Comment by mackmcconnell** [comment]
Thank you! It's a bogus password, though.

On Wed, Feb 3, 2016 at 1:11 AM, Benjamin Burns notifications@github.com
wrote:

> See config/application.yml
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mackmcconnell/yocuties/issues/1.

## 

Mack McConnell
@mackattaq http://twitter.com/mackattaq
Taster's Club http://www.tastersclub.com/
